// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwlwrtntkgzzxfczqdbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bHdydG50a2d6enhmY3pxZGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTY5MjYsImV4cCI6MjA2NTMzMjkyNn0.DyMDM-lKdk25sQyQaME29caHiEJqCyk7oDChVpzVnQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});